name: 'synthea_omop_etl'
version: '0.1.0'
config-version: 2

profile: 'synthea_omop_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

models:
  synthea_omop_etl:
    +materialized: table

seeds:
  synthea_omop_etl:
    synthea:
      +schema: synthea
      allergies:
        +column_types:
          CODE: varchar
          REACTION1: varchar
      careplans:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
      claims_transactions:
        +column_types:
          PROCEDURECODE: varchar
      claims:
        +column_types:
          DIAGNOSIS1: varchar
          DIAGNOSIS2: varchar
          DIAGNOSIS3: varchar
          DIAGNOSIS4: varchar
          DIAGNOSIS5: varchar
          DIAGNOSIS6: varchar
          DIAGNOSIS7: varchar
          DIAGNOSIS8: varchar
      conditions:
        +column_types:
          CODE: varchar
      devices:
        +column_types:
          CODE: varchar
      encounters:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
      imaging_studies:
        +column_types:
          CODE: varchar
          BODYSITE_CODE: varchar
          MODALITY_CODE: varchar
          SOP_CODE: varchar
          PROCEDURE_CODE: varchar
      immunizations:
        +column_types:
          CODE: varchar
      medications:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
      observations:
        +column_types:
          CODE: varchar
      patients:
        +column_types:
          SUFFIX: varchar
          ZIP: varchar
      procedures:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
      supplies:
        +column_types:
          CODE: varchar


          