name: 'synthea_omop_etl'
version: '0.1.0'
config-version: 2

profile: 'synthea_omop_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

vars:
  seed_source: true

models:
  synthea_omop_etl:
    +materialized: table

seeds:
  synthea_omop_etl:
    map:
      +enabled: true
      +schema: map_seeds
    vocabulary:
      +enabled: true
      +schema: vocab_seeds
    synthea:
      +enabled: true
      +schema: synthea_seeds
